export const siteConfig = {
  name: "Jabba",
  legalName: "",
  tagline: "",
  heroTitle: "Jabba",
  heroSubtitle: "Fruits, légumes, poissons et fruits de mer, viandes, céréales et épices — commandez en ligne, payez à la livraison.",
  seoDescription: "Jabba : fruits, légumes, produits halieutiques frais et transformés, charcuterie, céréales et épices. Commande en ligne, paiement à la livraison au Sénégal.",
  url: "",
  locale: "fr-FR",
  currency: { code: "XOF", label: "FCFA", decimals: 0 },
  country: "Sénégal",
  contact: { whatsapp: "", phone: "", email: "", address: "" },
  features: { negotiation: false, countryOfOrigin: false, onlinePayment: false },
  storageKeys: { cart: "jabba-cart", adminCookie: "jabba-admin-token" },
} as const;
