-- Jabba catalog seed — auto-generated by import-catalog.py
BEGIN TRANSACTION;

INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-001',
  'PROD-001',
  'Ailes de poulet',
  'Charcuterie',
  2300,
  2000,
  'kg',
  100,
  'kg',
  'Morceaux de poulet tendres, parfaits pour les grillades et les fritures.',
  'Les ailes de poulet sont riches en protéines et appréciées pour leur chair savoureuse. Elles peuvent être préparées grillées, frites, marinées ou braisées. À conserver entre 0 °C et 4 °C ou au congélateur.',
  '["/api/images/Charcuterie/Ailes de poulet.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-002',
  'PROD-002',
  'Blanc de poulet',
  'Charcuterie',
  6000,
  5500,
  'kg',
  100,
  'kg',
  'Viande blanche maigre, tendre et riche en protéines.',
  'Le blanc de poulet est une excellente source de protéines de haute qualité, pauvre en matières grasses. Il convient aux grillades, sautés, salades et plats mijotés.',
  '["/api/images/Charcuterie/Blanc de poulet.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-003',
  'PROD-003',
  'Corn boeuf',
  'Charcuterie',
  750,
  700,
  'Boîte',
  100,
  'kg',
  'Viande de bœuf en conserve, prête à consommer.',
  'Le corned-beef est préparé à partir de viande de bœuf assaisonnée et conservée. Il est pratique pour les repas rapides et peut être utilisé dans les sandwichs, salades ou plats cuisinés.',
  '["/api/images/Charcuterie/Corn boeuf.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-004',
  'PROD-004',
  'Cuisses de poulet 2',
  'Charcuterie',
  2200,
  2000,
  'Paquet',
  100,
  'kg',
  'Deux cuisses de poulet tendres et savoureuses.',
  'Les cuisses de poulet sont idéales pour les grillades, les sauces et les fritures. Leur chair est juteuse et riche en protéines.',
  '["/api/images/Charcuterie/Cuisses de poulet 2.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-005',
  'PROD-005',
  'Cuisses de poulet',
  'Charcuterie',
  1200,
  1100,
  'kg',
  100,
  'kg',
  'Morceaux de poulet à chair tendre et savoureuse.',
  'Les cuisses de poulet sont riches en protéines et adaptées à de nombreuses préparations culinaires. Elles doivent être conservées au froid.',
  '["/api/images/Charcuterie/Cuisses de poulet.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-006',
  'PROD-006',
  'Jambon',
  'Charcuterie',
  1000,
  900,
  'kg',
  100,
  'kg',
  'Charcuterie tendre et savoureuse.',
  'Le jambon est riche en protéines et en vitamines du groupe B. Il est idéal pour les sandwichs, pizzas, salades et plats cuisinés.',
  '["/api/images/Charcuterie/Jambon.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-007',
  'PROD-007',
  'Merguez',
  'Charcuterie',
  1600,
  1500,
  '1/2 kg',
  100,
  'kg',
  'Saucisse épicée à base de viande rouge.',
  'Les merguez sont préparées à partir de viande de bœuf ou de mouton assaisonnée. Elles sont idéales pour les grillades, les barbecues et les plats en sauce.',
  '["/api/images/Charcuterie/Merguez.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-008',
  'PROD-008',
  'Pigeons',
  'Charcuterie',
  5000,
  4700,
  'paire',
  100,
  'kg',
  'Viande tendre au goût raffiné.',
  'Le pigeon est une viande maigre, riche en protéines et en fer. Il est apprécié dans les plats traditionnels et gastronomiques.',
  '["/api/images/Charcuterie/Pigeons.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-009',
  'PROD-009',
  'Poulet de chair',
  'Charcuterie',
  2500,
  2300,
  'kg',
  100,
  'kg',
  'Poulet frais à chair tendre et savoureuse.',
  'Le poulet de chair est une excellente source de protéines. Il convient aux grillades, sauces, fritures et rôtis.',
  '["/api/images/Charcuterie/Poulet de chair.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-010',
  'PROD-010',
  'Saucisson de jambon rouge',
  'Charcuterie',
  2200,
  2000,
  'kg',
  100,
  'kg',
  'Charcuterie fumée à la saveur intense.',
  'Préparé à partir de jambon rouge, ce saucisson est riche en protéines et idéal pour les apéritifs, sandwichs et plateaux de charcuterie.',
  '["/api/images/Charcuterie/Saucisson de jambon rouge.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-011',
  'PROD-011',
  'Saucisson de jambon',
  'Charcuterie',
  2000,
  1800,
  'kg',
  100,
  'kg',
  'Charcuterie de jambon au goût délicat.',
  'Élaboré à partir de viande de jambon de qualité, il se déguste en tranches ou dans différentes préparations culinaires.',
  '["/api/images/Charcuterie/Saucisson de jambon.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-012',
  'PROD-012',
  'Saucisson',
  'Charcuterie',
  1800,
  1700,
  'kg',
  100,
  'kg',
  'Charcuterie savoureuse idéale pour les apéritifs.',
  'Le saucisson est préparé à partir de viande assaisonnée et séchée ou cuite selon la recette. Il est riche en protéines et se conserve au frais.',
  '["/api/images/Charcuterie/Saucisson.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-013',
  'PROD-013',
  'Viande bovine',
  'Charcuterie',
  4500,
  4200,
  'kg',
  100,
  'kg',
  'Viande rouge riche en protéines et en fer.',
  'La viande bovine est appréciée pour sa tendreté et sa valeur nutritionnelle. Elle convient aux grillades, ragoûts, brochettes et sauces.',
  '["/api/images/Charcuterie/Viande bovine.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-014',
  'PROD-014',
  'Viande de mouton et chèvre',
  'Charcuterie',
  4500,
  4300,
  'kg',
  100,
  'kg',
  'Viande rouge savoureuse, riche en protéines.',
  'La viande de mouton et de chèvre est idéale pour les grillades, les plats mijotés et les recettes traditionnelles.',
  '["/api/images/Charcuterie/Viande de mouton et chèvre.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-015',
  'PROD-015',
  'Viande hachée de boeuf',
  'Charcuterie',
  6000,
  5700,
  'kg',
  100,
  'kg',
  'Viande de bœuf finement hachée.',
  'Préparée à partir de morceaux soigneusement sélectionnés, elle est idéale pour les boulettes, hamburgers, sauces et farces.',
  '["/api/images/Charcuterie/Viande hachée de boeuf.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-016',
  'PROD-016',
  'Viande hachée de mouton',
  'Charcuterie',
  6200,
  6000,
  'kg',
  100,
  'kg',
  'Viande de mouton finement hachée.',
  'Sa texture tendre et son goût prononcé en font un excellent choix pour les keftas, brochettes et sauces.',
  '["/api/images/Charcuterie/Viande hachée de mouton.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-017',
  'PROD-017',
  'Confiture Madd Sucré',
  'Confitures',
  1200,
  1000,
  'Bocal 250g',
  100,
  'kg',
  'Confiture artisanale à base de madd.',
  'Préparée avec des fruits de madd et du sucre, elle offre une texture onctueuse et une saveur authentique. Idéale pour les tartines et les desserts.',
  '["/api/images/Confitures/Confiture Madd Sucré.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-018',
  'PROD-018',
  'Ail moulu',
  'Épices',
  6000,
  5700,
  'kg',
  100,
  'kg',
  'Ail finement broyé, prêt à l''emploi.',
  'Obtenu à partir de gousses d''ail séchées puis moulues, il est parfait pour assaisonner les sauces, marinades, viandes et légumes.',
  '["/api/images/Epices/Ail moulu.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-019',
  'PROD-019',
  'Ail',
  'Épices',
  900,
  800,
  'kg',
  100,
  'kg',
  'Bulbe aromatique indispensable en cuisine.',
  'L''ail est riche en composés antioxydants et en vitamines. Il est utilisé pour relever les plats et les marinades.',
  '["/api/images/Epices/Ail.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-020',
  'PROD-020',
  'crevette en poudre',
  'Épices',
  1000,
  900,
  'kg',
  100,
  'kg',
  'Condiment obtenu à partir de crevettes séchées moulues.',
  'La poudre de crevette apporte une saveur intense aux sauces, soupes et plats traditionnels. Elle est riche en protéines et en minéraux.',
  '["/api/images/Epices/crevette-en-poudre.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-021',
  'PROD-021',
  'poivre noir moulu',
  'Épices',
  7000,
  6700,
  'kg',
  100,
  'kg',
  'Épice finement moulue au goût intense.',
  'Le poivre noir moulu est utilisé pour relever les viandes, poissons, sauces et légumes. Il doit être conservé dans un récipient hermétique.',
  '["/api/images/Epices/poivre noir moulu.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-022',
  'PROD-022',
  'poivre noir',
  'Épices',
  6000,
  5750,
  'kg',
  100,
  'kg',
  'Baies de poivre noir au parfum puissant.',
  'Le poivre noir en grains conserve tout son arôme et peut être moulu au moment de l''utilisation pour relever tous les plats.',
  '["/api/images/Epices/poivre noir.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-023',
  'PROD-023',
  'Ananas',
  'Fruits',
  1500,
  1200,
  'kg',
  100,
  'kg',
  'Fruit tropical sucré et juteux.',
  'L''ananas est riche en vitamine C, en fibres et en bromélaïne. Il se consomme frais, en jus ou en desserts.',
  '["/api/images/Fruits/Ananas.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-024',
  'PROD-024',
  'Banane',
  'Fruits',
  900,
  750,
  'kg',
  100,
  'kg',
  'Fruit énergétique riche en potassium.',
  'La banane est une excellente source d''énergie, de fibres et de vitamines. Elle se consomme fraîche, en jus ou en pâtisserie.',
  '["/api/images/Fruits/Banane.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-025',
  'PROD-025',
  'Carresol',
  'Fruits',
  2000,
  1750,
  'kg',
  100,
  'kg',
  'Fruit tropical à chair sucrée et parfumée.',
  'Le carresol est apprécié pour sa chair juteuse et son goût délicat. Il est riche en vitamines et se consomme frais ou en jus.',
  '["/api/images/Fruits/Carresol.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-026',
  'PROD-026',
  'Ditakh',
  'Fruits',
  800,
  600,
  'kg',
  100,
  'kg',
  'Fruit sauvage au goût acidulé et rafraîchissant.',
  'Le ditakh est un fruit local très apprécié au Sénégal. Il est utilisé pour préparer des jus, des desserts et des boissons traditionnelles. Il est riche en vitamine C et en antioxydants.',
  '["/api/images/Fruits/Ditakh.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-027',
  'PROD-027',
  'fraises',
  'Fruits',
  6500,
  5000,
  'kg',
  100,
  'kg',
  'Petit fruit rouge parfumé, sucré et riche en vitamines.',
  'Les fraises sont riches en vitamine C, en fibres et en antioxydants. Elles se dégustent fraîches, en jus, en pâtisserie ou en confiture. Elles doivent être conservées au réfrigérateur pour préserver leur fraîcheur.',
  '["/api/images/Fruits/fraises.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-028',
  'PROD-028',
  'Framboise',
  'Fruits',
  10000,
  9000,
  'Kg',
  100,
  'kg',
  'Petit fruit rouge, sucré et légèrement acidulé, riche en vitamines et en antioxydants.',
  'La framboise est un fruit délicat apprécié pour sa saveur parfumée et sa richesse en vitamine C, en fibres et en antioxydants. Elle se consomme fraîche, en jus, en pâtisserie ou en confiture. À conserver au réfrigérateur pour préserver sa fraîcheur.',
  '["/api/images/Fruits/Framboise.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-029',
  'PROD-029',
  'Fruit du baobab',
  'Fruits',
  3500,
  3000,
  'Kg',
  100,
  'kg',
  'Fruit naturel riche en vitamine C, en fibres et en minéraux.',
  'Le fruit du baobab possède une pulpe blanche naturellement acidulée. Il est utilisé pour préparer des boissons, des desserts et des compléments alimentaires. Il est reconnu pour ses propriétés nutritives et énergétiques.',
  '["/api/images/Fruits/Fruit du baobab.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-030',
  'PROD-030',
  'Goyave 800x533',
  'Fruits',
  1000,
  800,
  'Kg',
  100,
  'kg',
  'Fruit tropical parfumé, riche en vitamine C et en fibres.',
  'La goyave est un fruit à chair blanche, rose ou rouge, apprécié pour son goût sucré et son parfum intense. Elle se consomme fraîche, en jus, en confiture ou dans les desserts. Sa richesse en vitamines et en antioxydants en fait un excellent fruit pour une alimentation équilibrée.',
  '["/api/images/Fruits/Goyave-800x533.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-031',
  'PROD-031',
  'Lim Tahiti',
  'Fruits',
  500,
  400,
  'Kg',
  100,
  'kg',
  'Agrume vert très parfumé, idéal pour les boissons et les assaisonnements.',
  'La Lime Tahiti est un citron vert sans pépins, reconnu pour son jus abondant et sa saveur acidulée. Elle est utilisée dans les jus, cocktails, sauces, marinades et pâtisseries.',
  '["/api/images/Fruits/Lim Tahiti.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-032',
  'PROD-032',
  'Madd',
  'Fruits',
  600,
  500,
  'Kg',
  100,
  'kg',
  'Fruit sauvage sénégalais à la pulpe sucrée et acidulée.',
  'Le madd est un fruit local très apprécié au Sénégal pour son goût unique. Sa pulpe est consommée fraîche ou transformée en jus, sirops, confitures et desserts. Il est naturellement riche en vitamine C et en antioxydants.',
  '["/api/images/Fruits/Madd.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-033',
  'PROD-033',
  'Mandarina 1 2 847x1024',
  'Fruits',
  600,
  500,
  'Kg',
  100,
  'kg',
  'Agrume sucré, juteux et facile à éplucher.',
  'La mandarine est riche en vitamine C, en fibres et en antioxydants. Elle est idéale pour une consommation fraîche, en jus ou dans les desserts. Son goût doux en fait un fruit apprécié de toute la famille.',
  '["/api/images/Fruits/Mandarina-1-2-847x1024.png"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-034',
  'PROD-034',
  'Mango Keitt',
  'Fruits',
  500,
  400,
  'Kg',
  100,
  'kg',
  'Mangue à chair ferme, sucrée et peu fibreuse.',
  'La mangue Keitt est une variété très appréciée pour sa chair abondante, juteuse et presque sans fibres. Elle est idéale pour être consommée fraîche, en jus, en salade de fruits ou en desserts.',
  '["/api/images/Fruits/Mango Keitt.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-035',
  'PROD-035',
  'Mangue Bouko Jékhal',
  'Fruits',
  700,
  500,
  'Kg',
  100,
  'kg',
  'Variété locale de mangue, sucrée et très parfumée.',
  'La mangue Bouko Jékhal est reconnue pour sa chair juteuse, son parfum intense et son goût naturellement sucré. Elle est excellente à déguster fraîche ou transformée en jus, confitures et nectar.',
  '["/api/images/Fruits/Mangue Bouko Jékhal.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-036',
  'PROD-036',
  'Mangue Diourou',
  'Fruits',
  700,
  600,
  'Kg',
  100,
  'kg',
  'Mangue locale à chair tendre et très parfumée.',
  'La mangue Diourou est une variété locale appréciée pour sa texture fondante, sa saveur sucrée et son parfum naturel. Elle est idéale pour la consommation fraîche et la transformation en jus, purées et confitures.',
  '["/api/images/Fruits/Mangue Diourou.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-037',
  'PROD-037',
  'Mangue Kent',
  'Fruits',
  600,
  500,
  'Kg',
  100,
  'kg',
  'Mangue à chair fondante, sucrée et peu fibreuse, idéale pour une consommation fraîche.',
  'La mangue Kent est une variété très appréciée pour sa chair juteuse, tendre et pratiquement sans fibres. Riche en vitamines A et C, en fibres et en antioxydants, elle se consomme fraîche, en jus, en salades de fruits ou en desserts. Elle doit être conservée à température ambiante jusqu''à maturité puis au réfrigérateur.',
  '["/api/images/Fruits/Mangue Kent.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-038',
  'PROD-038',
  'Melon',
  'Fruits',
  700,
  600,
  'Kg',
  100,
  'kg',
  'Fruit rafraîchissant, sucré et riche en eau, idéal pour les journées chaudes.',
  'Le melon est un fruit très apprécié pour sa chair parfumée, juteuse et naturellement sucrée. Il est une excellente source de vitamines A et C, de potassium et d''antioxydants. Il se consomme frais, en salades de fruits, en jus ou en desserts.',
  '["/api/images/Fruits/Melon.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-039',
  'PROD-039',
  'Orange Thomson',
  'Fruits',
  700,
  600,
  'Kg',
  100,
  'kg',
  'Orange juteuse et sucrée, riche en vitamine C.',
  'L''orange Thomson est une variété réputée pour son jus abondant, sa saveur douce et sa chair parfumée. Elle est riche en vitamine C, en fibres et en antioxydants. Elle se consomme fraîche ou en jus et contribue à une alimentation saine et équilibrée.',
  '["/api/images/Fruits/Orange Thomson.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-040',
  'PROD-040',
  'Papaye Vega F1',
  'Fruits',
  1200,
  1100,
  'Kg',
  100,
  'kg',
  'Papaye à chair orangée, sucrée et riche en vitamines.',
  'La papaye Vega F1 est une variété productive offrant des fruits à chair tendre, sucrée et parfumée. Elle est riche en vitamines A et C, en fibres et en enzymes naturelles favorisant la digestion. Elle se consomme fraîche, en jus ou en desserts.',
  '["/api/images/Fruits/Papaye Vega F1.png"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-041',
  'PROD-041',
  'PASSIFLORE 1',
  'Fruits',
  3500,
  3000,
  'Kg',
  100,
  'kg',
  'Fruit de la passion au goût sucré et légèrement acidulé.',
  'La passiflore est un fruit tropical reconnu pour sa pulpe parfumée, riche en vitamine C, en fibres et en antioxydants. Elle est utilisée dans les jus, les desserts, les confitures et les salades de fruits. À conserver dans un endroit frais après récolte.',
  '["/api/images/Fruits/PASSIFLORE 1.jpg"]',
  'IN_STOCK',
  0,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-042',
  'PROD-042',
  'Passiflore',
  'Fruits',
  3500,
  3000,
  'Kg',
  100,
  'kg',
  'Fruit tropical parfumé, apprécié pour sa saveur unique et rafraîchissante.',
  'Le fruit de la passion est riche en vitamines, en minéraux et en fibres alimentaires. Sa pulpe juteuse et parfumée est idéale pour les jus, les cocktails, les desserts, les yaourts et les pâtisseries.',
  '["/api/images/Fruits/Passiflore.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-043',
  'PROD-043',
  'pasteques',
  'Fruits',
  200,
  150,
  'Kg',
  100,
  'kg',
  'Fruit très rafraîchissant, riche en eau et naturellement sucré.',
  'La pastèque est un fruit d''été très apprécié pour sa chair rouge, croquante et juteuse. Riche en eau, en vitamines A et C ainsi qu''en antioxydants, elle est idéale pour l''hydratation. Elle se consomme fraîche, en jus ou en salades de fruits.',
  '["/api/images/Fruits/pasteques.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-044',
  'PROD-044',
  'Poire',
  'Fruits',
  2300,
  2000,
  'Kg',
  100,
  'kg',
  'Fruit à chair tendre, juteuse et naturellement sucrée.',
  'La poire est riche en fibres, en vitamine C et en antioxydants. Elle se consomme fraîche, en compote, en pâtisserie ou en salade de fruits. Sa texture fondante et son goût délicat en font un fruit apprécié par toute la famille.',
  '["/api/images/Fruits/Poire.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-045',
  'PROD-045',
  'POMELO',
  'Fruits',
  600,
  500,
  'Kg',
  100,
  'kg',
  'Agrume à chair juteuse, légèrement sucrée et acidulée.',
  'Le pomelo est un agrume riche en vitamine C, en fibres et en antioxydants. Il est apprécié pour sa chair rafraîchissante et son goût équilibré entre douceur et acidité. Il se consomme frais, en jus ou dans les salades de fruits. Il doit être conservé dans un endroit frais et sec afin de préserver sa qualité.',
  '["/api/images/Fruits/POMELO.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-046',
  'PROD-046',
  'pomme',
  'Fruits',
  1200,
  1100,
  'Kg',
  100,
  'kg',
  'Fruit croquant, sucré ou légèrement acidulé, très consommé frais. C''est l''un des fruits importés les plus populaires sur les étals sénégalais.',
  'La pomme est un fruit à peau rouge, verte ou jaune. Elle est consommée fraîche, en jus ou en pâtisserie. Généralement importée et vendue en vrac ou en cageots.',
  '["/api/images/Fruits/pomme.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-047',
  'PROD-047',
  'raisin',
  'Fruits',
  3500,
  3250,
  'Kg',
  100,
  'kg',
  'Fruit de table délicat et sucré, disponible en variétés blanches, rouges ou noires, avec ou sans pépins.',
  'Issu principalement d''importations (Italie, Espagne, Afrique du Sud), le raisin est apprécié pour sa fraîcheur et sa teneur élevée en antioxydants. Très sensible aux chocs, il est transporté et commercialisé en chaîne du froid, puis conditionné en barquettes perforées de 500 g ou de 1 kg pour protéger les grappes.',
  '["/api/images/Fruits/raisin-.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-048',
  'PROD-048',
  'Tangelo',
  'Fruits',
  700,
  600,
  'Kg',
  100,
  'kg',
  'Agrume hybride issu du croisement entre une mandarine et un pomélo, caractérisé par sa forme légèrement mamelonnée et sa forte teneur en jus.',
  'Ce fruit possède une écorce orange vif facile à peler et une pulpe extrêmement juteuse, douce et acidulée. Consommé frais ou pressé en jus, il provient en partie des productions locales d''agrumes en Casamance ou dans la zone des Niayes, ainsi que d''importations régionales, et se conserve bien à température ambiante.',
  '["/api/images/Fruits/Tangelo.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-049',
  'PROD-049',
  'Aubergine amer',
  'Légumes & Aromates',
  600,
  500,
  'Kg',
  100,
  'kg',
  'Petit légume local de couleur verte à jaune-orangé, indispensable pour apporter une touche d''amertume caractéristique aux plats traditionnels.',
  'Couramment appelée Diakhatou au Sénégal, cette aubergine (Solanum aethiopicum) est cultivée localement de manière intensive dans la zone des Niayes. Elle s''utilise principalement entière dans la préparation du Thiéboudienne ou écrasée dans les sauces, et est commercialisée en vrac sur les étals ou regroupée en petits tas sur les marchés.',
  '["/api/images/Légumes & Aromates/Aubergine amer.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-050',
  'PROD-050',
  'Aubergine',
  'Légumes & Aromates',
  800,
  700,
  'Kg',
  100,
  'kg',
  'Grand légume allongé à la peau violette et brillante, doté d''une chair tendre qui absorbe magnifiquement les saveurs des sauces.',
  'Cultivée à grande échelle dans les zones maraîchères du pays, l''aubergine classique est un ingrédient de base du Thiéboudienne et de divers ragoûts de légumes. Elle nécessite une manipulation soignée pour éviter les flétrissures et est livrée sur les marchés dans des sacs en toile de jute ou des caisses en plastique avant d''être vendue à la pièce ou au kilogramme.',
  '["/api/images/Légumes & Aromates/Aubergine.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-051',
  'PROD-051',
  'Carottes',
  'Légumes & Aromates',
  700,
  600,
  'Kg',
  100,
  'kg',
  'Racine potagère croquante de couleur orange, appréciée pour sa saveur douce et sa richesse en bêta-carotène.',
  'La production locale issue de la zone des Niayes approvisionne massivement le marché pendant la saison fraîche, complétée par des importations le reste de l''année. Utilisée crue en salade ou cuite dans le riz au poisson, elle est lavée, calibrée et vendue en vrac, ou présentée en sachets transparents d''un kilogramme.',
  '["/api/images/Légumes & Aromates/Carottes.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-052',
  'PROD-052',
  'Chou',
  'Légumes & Aromates',
  600,
  500,
  'Pièce',
  100,
  'kg',
  ': Légume feuille dense et compact formant une pomme serrée, très utilisé dans la cuisine sénégalaise quotidienne.',
  'Le chou blanc pommé est un pilier du maraîchage local au Sénégal, récolté principalement durant les premiers mois de l''année. C''est un morceau indispensable du Thiéboudienne et du Kandia ; il est transporté en vrac dans des camions et vendu à l''unité selon le calibre de la pomme sur les marchés de gros et de détail.',
  '["/api/images/Légumes & Aromates/Chou.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-053',
  'PROD-053',
  'Comcombre',
  'Légumes & Aromates',
  800,
  700,
  'Kg',
  100,
  'kg',
  'Légume d''eau allongé et très rafraîchissant, consommé presque exclusivement cru en entrée ou en salade.',
  'Produit localement tout au long de l''année grâce aux exploitations irriguées des Niayes, le concombre possède une peau verte et une chair croquante pauvre en calories. Il est récolté avant pleine maturité pour préserver sa fermeté, lavé et exposé à l''ombre sur les étals pour éviter la déshydratation.',
  '["/api/images/Légumes & Aromates/Comcombre.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-054',
  'PROD-054',
  'Courge   Nadio',
  'Légumes & Aromates',
  500,
  450,
  'Kg',
  100,
  'kg',
  'Variété locale de courge ou de potiron à la chair orange et sucrée, massivement utilisée dans les sauces et les plats de riz.',
  'Le Nadio est une courge tropicale rustique cultivée dans les exploitations agroécologiques et maraîchères du Sénégal. Sa chair ferme et douce s''intègre parfaitement aux sauces de poissons ou de viandes ; en raison de son volume imposant, elle est souvent découpée et vendue en tranches prêtes à l''emploi sur les marchés locaux, bien qu''elle se conserve des mois entiers.',
  '["/api/images/Légumes & Aromates/Courge - Nadio.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-055',
  'PROD-055',
  'Feuilles de salades',
  'Légumes & Aromates',
  1500,
  1300,
  'kg',
  100,
  'kg',
  'Salade verte locale fraîche, incontournable pour les entrées.',
  'Variétés de laitue tendres et croquantes. Cultivée dans les Niayes. Utilisée crue ou pour accompagner le dibi.',
  '["/api/images/Légumes & Aromates/Feuilles de salades.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-056',
  'PROD-056',
  'Gombo',
  'Légumes & Aromates',
  800,
  700,
  'kg',
  100,
  'kg',
  'Légume local d''Afrique de l''Ouest appelé Kandja.',
  'Petits fruits verts allongés. Cultivé en Casamance et dans les Niayes. Base de la sauce Soupe Kandja.',
  '["/api/images/Légumes & Aromates/Gombo.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-057',
  'PROD-057',
  'Manioc frais',
  'Légumes & Aromates',
  400,
  350,
  'kg',
  100,
  'kg',
  'Racine tubéreuse lourde et très riche en amidon.',
  'Écorce brune et chair blanche dense. Originaire de Thiès ou Kaolack. Accompagne le Thiéboudienne ou se mange bouilli.',
  '["/api/images/Légumes & Aromates/Manioc frais.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-058',
  'PROD-058',
  'Navet blanc',
  'Légumes & Aromates',
  500,
  400,
  'kg',
  100,
  'kg',
  'Légume racine croquant et légèrement piquant.',
  'Racine blanche et ferme. Issu du maraîchage des Niayes. Indispensable pour le Thiéboudienne et les ragoûts.',
  '["/api/images/Légumes & Aromates/Navet blanc.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-059',
  'PROD-059',
  'Oignon 1',
  'Légumes & Aromates',
  700,
  600,
  'kg',
  100,
  'kg',
  'Oignon local de conservation issu de la campagne nationale.',
  'Bulbe jaune/doré ferme à saveur prononcée. Produit à Potou et dans la Vallée. Base absolue pour le Yassa et les sauces.',
  '["/api/images/Légumes & Aromates/Oignon 1.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-060',
  'PROD-060',
  'Oignon',
  'Légumes & Aromates',
  900,
  800,
  'kg',
  100,
  'kg',
  'Oignon importé utilisé en période de soudure.',
  'Bulbes réguliers à peau sèche bien calibrée. Importé des Pays-Bas ou du Maroc. Utilisé pour compléter le marché local.',
  '["/api/images/Légumes & Aromates/Oignon.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-061',
  'PROD-061',
  'Patates douces',
  'Légumes & Aromates',
  500,
  400,
  'kg',
  100,
  'kg',
  'Tubercule doux au goût naturellement sucré.',
  'Peau rose/brune et chair blanche ou orangée. Cultivée dans les Niayes. Ajoutée au Thiéboudienne ou consommée frite.',
  '["/api/images/Légumes & Aromates/Patates douces.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-062',
  'PROD-062',
  'persils1',
  'Légumes & Aromates',
  1500,
  1250,
  'kg',
  100,
  'kg',
  'Herbe aromatique fraîche au parfum très prononcé.',
  'Feuilles vertes découpées (plat ou frisé). Cultivé en banlieue de Dakar. Ingrédient majeur du Nokkoss pour farcir le poisson.',
  '["/api/images/Légumes & Aromates/persils1.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-063',
  'PROD-063',
  'Piment Goana',
  'Légumes & Aromates',
  2500,
  2250,
  'kg',
  100,
  'kg',
  'Petite variété de piment local très piquant et aromatique.',
  'Fruit charnu vert ou rouge vif à maturité. Produit dans la zone des Niayes. Utilisé comme rehausseur de goût sur la table.',
  '["/api/images/Légumes & Aromates/Piment Goana.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-064',
  'PROD-064',
  'Piment rouge et vert',
  'Légumes & Aromates',
  1000,
  800,
  'kg',
  100,
  'kg',
  'Piments frais au goût relevé, idéals pour assaisonner les plats.',
  'Les piments rouges et verts sont des légumes très utilisés dans la cuisine sénégalaise. Riches en vitamine C et en antioxydants, ils apportent une saveur piquante et une touche de couleur aux sauces, marinades et plats traditionnels. À conserver au frais pour préserver leur fraîcheur.',
  '["/api/images/Légumes & Aromates/Piment rouge et vert.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-065',
  'PROD-065',
  'Piment Sofia',
  'Légumes & Aromates',
  2500,
  2300,
  'kg',
  100,
  'kg',
  'Variété de piment très parfumée, appréciée pour son piquant modéré.',
  'Le piment Sofia est une variété locale reconnue pour son arôme intense et son goût équilibré. Il est utilisé frais dans les sauces, les grillades et les préparations culinaires. Il est riche en vitamines A et C et doit être conservé dans un endroit frais.',
  '["/api/images/Légumes & Aromates/Piment Sofia.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-066',
  'PROD-066',
  'Piment thioukouli',
  'Légumes & Aromates',
  1000,
  800,
  'kg',
  100,
  'kg',
  'Petit piment très fort, idéal pour relever les plats traditionnels.',
  'Le piment Thioukouli est une variété très piquante, largement utilisée dans la cuisine sénégalaise. Son parfum intense et sa forte concentration en capsaïcine en font un excellent condiment. Il se consomme frais, séché ou moulu.',
  '["/api/images/Légumes & Aromates/Piment thioukouli.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-067',
  'PROD-067',
  'Poireau mince oignons',
  'Légumes & Aromates',
  700,
  600,
  'kg',
  100,
  'kg',
  'Jeunes tiges tendres au goût délicat, idéales pour les salades et les sauces',
  'Les jeunes poireaux ou jeunes oignons sont appréciés pour leur saveur douce et leur richesse en vitamines et minéraux. Ils accompagnent parfaitement les salades, soupes, sauces et plats mijotés. À conserver au réfrigérateur.',
  '["/api/images/Légumes & Aromates/Poireau mince-oignons.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-068',
  'PROD-068',
  'Poireau',
  'Légumes & Aromates',
  1200,
  1000,
  'kg',
  100,
  'kg',
  'Légume frais à la saveur douce, idéal pour les soupes et les plats mijotés.',
  'Le poireau est un légume riche en fibres, vitamines A, C et K ainsi qu''en minéraux. Il est utilisé dans les soupes, les sauces, les gratins et les plats traditionnels. Il se conserve plusieurs jours au réfrigérateur.',
  '["/api/images/Légumes & Aromates/Poireau.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-069',
  'PROD-069',
  'Poivron',
  'Légumes & Aromates',
  1200,
  1100,
  'kg',
  100,
  'kg',
  'Légume croquant et parfumé, disponible en plusieurs couleurs.',
  'Le poivron est riche en vitamine C, en vitamine A et en antioxydants. Il est utilisé dans les salades, sauces, sautés, grillades et plats mijotés. Sa chair croquante et légèrement sucrée en fait un ingrédient très apprécié.',
  '["/api/images/Légumes & Aromates/Poivron .jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-070',
  'PROD-070',
  'Pomme de terre',
  'Légumes & Aromates',
  900,
  800,
  'kg',
  100,
  'kg',
  'Tubercule nourrissant, idéal pour de nombreuses préparations culinaires.',
  'La pomme de terre est une excellente source de glucides, de fibres, de potassium et de vitamines. Polyvalente, elle peut être cuite à l''eau, frite, rôtie, sautée ou réduite en purée. À conserver dans un endroit frais, sec et à l''abri de la lumière.',
  '["/api/images/Légumes & Aromates/Pomme de terre.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-071',
  'PROD-071',
  'Tomates',
  'Légumes & Aromates',
  1200,
  1100,
  'kg',
  100,
  'kg',
  'Tomates fraîches, juteuses et riches en vitamines, idéales pour toutes les préparations.',
  'Les tomates sont des légumes-fruits très appréciés pour leur saveur, leur richesse en vitamines A et C ainsi qu''en lycopène, un puissant antioxydant. Elles sont utilisées dans les salades, sauces, jus et plats cuisinés. À conserver à température ambiante ou au frais selon leur degré de maturité.',
  '["/api/images/Légumes & Aromates/Tomates.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-072',
  'PROD-072',
  'Barracuda (Séd)',
  'Produits halieutiques frais',
  6000,
  5700,
  'kg',
  100,
  'kg',
  'Poisson de mer à chair ferme, blanche et savoureuse, idéal pour les grillades et les sauces.',
  'Le barracuda est un poisson très apprécié pour sa chair ferme, maigre et riche en protéines de haute qualité. Il constitue une bonne source d''oméga-3, de phosphore, de sélénium et de vitamines du groupe B. Il peut être préparé grillé, frit, braisé ou en sauce. Pour préserver sa fraîcheur, il doit être conservé au réfrigérateur entre 0 °C et 4 °C ou au congélateur.',
  '["/api/images/Produits halieutiques Frais/Barracuda (Séd).jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-073',
  'PROD-073',
  'Crabes  bleu',
  'Produits halieutiques frais',
  3500,
  3200,
  'pièce',
  100,
  'kg',
  'Crabe marin à chair savoureuse, vendu frais ou vivant selon l’approvisionnement.',
  'Crustacé de mer apprécié pour sa chair fine et parfumée. Il est généralement commercialisé frais, vivant ou réfrigéré, en fonction de la pêche et de la disponibilité sur les marchés côtiers. Utilisé pour les soupes, sauces, grillades et préparations locales.',
  '["/api/images/Produits halieutiques Frais/Crabes  bleu.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-074',
  'PROD-074',
  'Crevettes',
  'Produits halieutiques frais',
  6000,
  5500,
  'kg',
  100,
  'kg',
  'Produit de la mer très demandé, à chair délicate et cuisson rapide.',
  'Les crevettes sont vendues décortiquées ou non, fraîches, réfrigérées ou congelées. Elles sont utilisées dans les plats mijotés, les sauces, les sautés et les grillades. Le conditionnement varie du vrac au sachet sous glace.',
  '["/api/images/Produits halieutiques Frais/Crevettes.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-075',
  'PROD-075',
  'Dorade grise',
  'Produits halieutiques frais',
  2500,
  2300,
  'kg',
  100,
  'kg',
  'Poisson de mer à chair ferme et goût fin.',
  'Poisson côtier très apprécié pour sa chair blanche et peu grasse. Il est vendu entier, frais ou réfrigéré, et convient à la friture, au braisage, au four ou à la cuisson en sauce.',
  '["/api/images/Produits halieutiques Frais/Dorade grise .jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-076',
  'PROD-076',
  'Dorade Rose',
  'Produits halieutiques frais',
  3000,
  2700,
  'kg',
  100,
  'kg',
  'Poisson de qualité à chair tendre et savoureuse.',
  'Espèce marine recherchée pour sa texture agréable et son goût délicat. Elle est généralement vendue entière, écaillée ou non, en frais ou sous glace. Elle s’utilise en grillade, cuisson au four, sauce ou fumage léger.',
  '["/api/images/Produits halieutiques Frais/Dorade Rose.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-077',
  'PROD-077',
  'Huîtres de palétuviers',
  'Produits halieutiques frais',
  1500,
  1200,
  'douzaine',
  100,
  'kg',
  'Huîtres issues des mangroves, consommées fraîches ou transformées.',
  'Mollusques bivalves récoltés dans les zones de palétuviers. Elles sont souvent commercialisées en grappes, en douzaine ou au kilo selon les habitudes locales. Elles se consomment fraîches, grillées, pochées ou intégrées à des sauces.',
  '["/api/images/Produits halieutiques Frais/Huîtres de palétuviers.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-078',
  'PROD-078',
  'Langoustes (Rose)',
  'Produits halieutiques frais',
  12000,
  NULL,
  'pièce',
  100,
  'kg',
  'Langouste de mer à forte valeur commerciale.',
  'Crustacé de grande taille à chair blanche et délicate, très prisé sur les marchés et en restauration. Elle est vendue vivante, fraîche ou réfrigérée, souvent à la pièce. Elle se prête aux grillades, cuissons vapeur, sauces et plats festifs.',
  '["/api/images/Produits halieutiques Frais/Langoustes (Rose).jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-079',
  'PROD-079',
  'Langoustes (Vertes)',
  'Produits halieutiques frais',
  10000,
  9000,
  'pièce',
  100,
  'kg',
  'Langouste marine recherchée, vendue entière et fraîche.',
  'La langouste verte est un produit haut de gamme vendu surtout entier, vivant ou frais. Sa chair est ferme, fine et adaptée aux préparations simples qui valorisent sa qualité naturelle. Conditionnement fréquent : vrac, caisse isotherme ou sur glace.',
  '["/api/images/Produits halieutiques Frais/Langoustes (Vertes).jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-080',
  'PROD-080',
  'LE POULPE',
  'Produits halieutiques frais',
  4500,
  4200,
  'kg',
  100,
  'kg',
  'Céphalopode à chair ferme, utilisé dans de nombreuses recettes.',
  'Le poulpe est vendu frais, nettoyé ou entier, parfois sur glace. Il nécessite souvent une pré-cuisson pour attendrir la chair avant grillade, ragoût, sauce ou salade. Produit apprécié dans la cuisine locale et la restauration.',
  '["/api/images/Produits halieutiques Frais/LE-POULPE.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-081',
  'PROD-081',
  'Mulet',
  'Produits halieutiques frais',
  1800,
  1500,
  'kg',
  100,
  'kg',
  'Poisson de mer ou d’estuaire, économique et polyvalent.',
  'Poisson courant sur les marchés sénégalais, vendu entier, frais ou réfrigéré. Sa chair est correcte, avec une utilisation fréquente en friture, braisage, sauce ou fumage selon la taille et la qualité.',
  '["/api/images/Produits halieutiques Frais/Mulet.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-082',
  'PROD-082',
  'Mâchoiron',
  'Produits halieutiques frais',
  3000,
  2700,
  'kg',
  100,
  'kg',
  'Poisson d''eau douce à chair tendre et savoureuse.',
  'Le mâchoiron est un poisson apprécié pour sa chair ferme et son goût délicat. Riche en protéines, en vitamines et en minéraux, il est idéal pour les grillades, les sauces et les fritures. À conserver au frais ou au congélateur.',
  '["/api/images/Produits halieutiques Frais/Mâchoiron.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-083',
  'PROD-083',
  'Rouget',
  'Produits halieutiques frais',
  2500,
  2400,
  'kg',
  100,
  'kg',
  'Poisson de mer à chair fine, tendre et très savoureuse.',
  'Le rouget est un poisson très apprécié pour sa chair délicate et parfumée. Il est riche en protéines, en oméga-3 et en vitamines. Il peut être préparé grillé, frit ou en sauce.',
  '["/api/images/Produits halieutiques Frais/Rouget.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-084',
  'PROD-084',
  'Seiche',
  'Produits halieutiques frais',
  5000,
  4700,
  'kg',
  100,
  'kg',
  'Mollusque à chair tendre, idéal pour les sauces et les grillades.',
  'La seiche est un mollusque marin riche en protéines, en minéraux et pauvre en matières grasses. Elle est utilisée dans les sauces, les grillades et les plats mijotés. Elle doit être conservée au froid pour préserver sa qualité.',
  '["/api/images/Produits halieutiques Frais/Seiche.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-085',
  'PROD-085',
  'Sole',
  'Produits halieutiques frais',
  4000,
  3700,
  'kg',
  100,
  'kg',
  'Poisson à chair blanche, fine et très tendre.',
  'La sole est un poisson noble apprécié pour sa chair délicate et son goût raffiné. Elle est riche en protéines, en vitamines B et en phosphore. Elle est idéale pour les grillades, les fritures et les cuissons à la vapeur.',
  '["/api/images/Produits halieutiques Frais/Sole.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-086',
  'PROD-086',
  'Sompat',
  'Produits halieutiques frais',
  2000,
  1500,
  'kg',
  100,
  'kg',
  'Poisson de mer à chair ferme et savoureuse.',
  'Le sompat est un poisson couramment consommé au Sénégal. Il est riche en protéines et convient parfaitement aux grillades, aux sauces et aux fritures.',
  '["/api/images/Produits halieutiques Frais/Sompat.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-087',
  'PROD-087',
  'Thiof',
  'Produits halieutiques frais',
  4200,
  4000,
  'kg',
  100,
  'kg',
  'Poisson noble très apprécié pour sa chair ferme et délicate.',
  'Le thiof (mérou blanc) est l''un des poissons les plus prisés au Sénégal. Sa chair est riche en protéines, pauvre en matières grasses et idéale pour le thiéboudienne, les grillades ou les filets.',
  '["/api/images/Produits halieutiques Frais/Thiof.avif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-088',
  'PROD-088',
  'Tilapia',
  'Produits halieutiques frais',
  2000,
  1500,
  'kg',
  100,
  'kg',
  'Poisson d''eau douce à chair tendre et peu grasse.',
  'Le tilapia est riche en protéines, en phosphore et en vitamines. Il est très apprécié pour les grillades, les fritures et les sauces.',
  '["/api/images/Produits halieutiques Frais/Tilapia.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-089',
  'PROD-089',
  'Yaboy (Sardinelle)',
  'Produits halieutiques frais',
  1800,
  1500,
  'kg',
  100,
  'kg',
  'Petit poisson de mer très consommé au Sénégal.',
  'Le yaboy, ou sardinelle, est riche en protéines, en oméga-3 et en calcium. Il est idéal pour les grillades, les fritures, les sauces et le thiéboudienne.',
  '["/api/images/Produits halieutiques Frais/Yaboy (Sardinelle).webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-090',
  'PROD-090',
  'crevettes sechees',
  'Produits halieutiques transformés',
  10000,
  9500,
  'kg',
  100,
  'kg',
  'Crevettes séchées au goût intense, idéales pour relever les plats.',
  'Les crevettes séchées sont riches en protéines et en minéraux. Elles sont utilisées comme condiment dans les sauces, les soupes et les plats traditionnels. À conserver dans un endroit sec.',
  '["/api/images/Produits halieutiques Transformés/crevettes sechees.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-091',
  'PROD-091',
  'Guedj',
  'Produits halieutiques transformés',
  2200,
  2000,
  'Sachet de 500 g',
  100,
  'kg',
  'Poisson fermenté et séché, incontournable de la cuisine sénégalaise.',
  'Le guedj est un poisson fermenté puis séché, utilisé pour relever les sauces et les plats traditionnels. Son goût puissant apporte une saveur authentique aux préparations culinaires.',
  '["/api/images/Produits halieutiques Transformés/Guedj.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-092',
  'PROD-092',
  'Le Yet',
  'Produits halieutiques transformés',
  5000,
  4700,
  'Kg',
  100,
  'kg',
  'Mollusque séché très utilisé comme condiment traditionnel.',
  'Le yet est un mollusque fermenté et séché, très apprécié dans la cuisine sénégalaise. Il apporte une saveur intense aux sauces, notamment au thiéboudienne.',
  '["/api/images/Produits halieutiques Transformés/Le-Yet.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-093',
  'PROD-093',
  'Paagn',
  'Produits halieutiques transformés',
  3500,
  3200,
  'Kg',
  100,
  'kg',
  'Coquillage séché au goût prononcé, utilisé comme condiment.',
  'Le paagn est un produit de la mer séché, riche en protéines et en minéraux. Il est principalement utilisé pour parfumer les sauces et les plats traditionnels.',
  '["/api/images/Produits halieutiques Transformés/Paagn.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-094',
  'PROD-094',
  'PINTON',
  'Produits halieutiques transformés',
  3000,
  2900,
  'Kg',
  100,
  'kg',
  'Poisson frais à chair tendre, idéal pour les préparations quotidiennes.',
  'Le pinton est un poisson apprécié pour sa chair savoureuse et sa polyvalence en cuisine. Il peut être préparé frit, grillé ou en sauce.',
  '["/api/images/Produits halieutiques Transformés/PINTON.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-095',
  'PROD-095',
  'Poudre de poisson',
  'Produits halieutiques transformés',
  2500,
  2300,
  'Kg',
  100,
  'kg',
  'Condiment obtenu à partir de poisson séché finement moulu.',
  'La poudre de poisson est utilisée pour enrichir les sauces, soupes et plats traditionnels. Elle est riche en protéines, en calcium et en minéraux. À conserver dans un récipient hermétique.',
  '["/api/images/Produits halieutiques Transformés/Poudre de poisson.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-096',
  'PROD-096',
  'Sardines conserves',
  'Produits halieutiques transformés',
  1200,
  1150,
  'Boîte de 125g',
  100,
  'kg',
  'Sardines prêtes à consommer, riches en protéines et en oméga-3.',
  'Les sardines en conserve sont pratiques et nutritives. Elles sont riches en protéines, en calcium, en oméga-3 et en vitamines. Elles peuvent être consommées seules ou intégrées dans diverses préparations culinaires.',
  '["/api/images/Produits halieutiques Transformés/Sardines conserves.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-097',
  'PROD-097',
  'Sel de mer',
  'Produits halieutiques transformés',
  900,
  800,
  'Sachet de 600 g',
  100,
  'kg',
  'Sel marin naturel, idéal pour l''assaisonnement et la conservation des aliments.',
  'Le sel de mer est obtenu par évaporation naturelle de l''eau de mer. Il est utilisé pour assaisonner les plats et pour la conservation des aliments. À conserver dans un endroit sec.',
  '["/api/images/Produits halieutiques Transformés/Sel de mer.avif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-098',
  'PROD-098',
  'Tambadiang',
  'Produits halieutiques transformés',
  2000,
  1750,
  'Sachet de 200 g',
  100,
  'kg',
  'Poisson de mer à chair ferme et savoureuse.',
  'Le tambadiang est un poisson apprécié pour sa chair riche en protéines et son goût délicat. Il convient parfaitement aux grillades, aux sauces et aux fritures.',
  '["/api/images/Produits halieutiques Transformés/Tambadiang.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-099',
  'PROD-099',
  'THON Blanc',
  'Produits halieutiques transformés',
  5000,
  4750,
  'kg',
  100,
  'kg',
  'Poisson de mer à chair blanche, ferme et riche en protéines.',
  'Le thon blanc est reconnu pour sa chair tendre, sa faible teneur en matières grasses et sa richesse en protéines et en oméga-3. Il est idéal pour les grillades, les steaks de poisson, les salades et les sauces.',
  '["/api/images/Produits halieutiques Transformés/THON Blanc.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-100',
  'PROD-100',
  'Toufa',
  'Produits halieutiques transformés',
  7000,
  NULL,
  'Kg',
  100,
  'kg',
  'Fruit de mer très apprécié pour sa saveur et sa valeur nutritive.',
  'Produit halieutique récolté sur les côtes sénégalaises. Riche en protéines, minéraux et oligo-éléments. Consommé frais ou transformé.',
  '["/api/images/Produits halieutiques Transformés/Toufa.webp"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-101',
  'PROD-101',
  'bissap rouge sachet',
  'Produits végétaux transformés',
  750,
  650,
  'Kg',
  100,
  'kg',
  'Fleur séchée utilisée pour la préparation de boissons naturelles.',
  'Calices d’hibiscus séchés utilisés pour les jus, infusions et sirops. Riches en antioxydants.',
  '["/api/images/Produits végétaux transformés/bissap-rouge-sachet.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-102',
  'PROD-102',
  'Poudre de Baobab',
  'Produits végétaux transformés',
  1400,
  1300,
  'Kg',
  100,
  'kg',
  'Poudre naturelle riche en vitamines et fibres.',
  'Obtenue à partir de la pulpe du fruit du baobab. Utilisée dans les préparations alimentaires ( couscous sénégalais).',
  '["/api/images/Produits végétaux transformés/Poudre de Baobab.avif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-103',
  'PROD-103',
  'Poudre de Moringa',
  'Produits végétaux transformés',
  800,
  700,
  'Kg',
  100,
  'kg',
  'Complément alimentaire riche en nutriments.',
  'Produite à partir de feuilles séchées et moulues. Source de protéines, vitamines et minéraux.',
  '["/api/images/Produits végétaux transformés/Poudre de Moringa.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-104',
  'PROD-104',
  'araw granule de farine de mil',
  'céréales',
  1750,
  1600,
  'Kg',
  100,
  'kg',
  'Produit traditionnel prêt à cuire.',
  'Granulés de mil destinés à la préparation du thiacry et d’autres mets locaux.',
  '["/api/images/céréales/araw-granule-de-farine-de-mil.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-105',
  'PROD-105',
  'Maiïs',
  'céréales',
  1600,
  1500,
  'Pot de  800g',
  100,
  'kg',
  'Céréale de base utilisée dans l’alimentation.',
  'Utilisé pour la fabrication de farine, couscous et bouillies.',
  '["/api/images/céréales/Maiïs.jpg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-106',
  'PROD-106',
  'Riz 11',
  'céréales',
  800,
  750,
  'Kg',
  1000,
  'kg',
  'Riz local destiné à la consommation quotidienne.',
  'Riz décortiqué, trié et cuit très rapidement en 11minutes',
  '["/api/images/céréales/Riz 11.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-107',
  'PROD-107',
  'Riz 12',
  'céréales',
  750,
  700,
  'Kg',
  1000,
  'kg',
  'Riz apprécié pour sa texture et sa polyvalence.',
  'Convient aux ménages et à la restauration.',
  '["/api/images/céréales/Riz 12.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-108',
  'PROD-108',
  'Riz 14',
  'céréales',
  24500,
  24000,
  'Sac 50 Kg',
  1000,
  'kg',
  'Riz de qualité supérieure.',
  'Présente une bonne homogénéité des grains et une excellente tenue à la cuisson.',
  '["/api/images/céréales/Riz 14.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-109',
  'PROD-109',
  'Riz 15',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz "Fine Brisure" (riz brisé) produit localement dans la vallée du fleuve au Sénégal.',
  'Il s''agit de brisures de riz (grains cassés lors de l''usinage), une texture particulièrement appréciée et incontournable dans la cuisine sénégalaise pour préparer le plat national, le Thiébou Dienn (riz au poisson) ou le Thiébou Yapp (riz à la viande).',
  '["/api/images/céréales/Riz 15.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-110',
  'PROD-110',
  'Riz 2',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'riz de la Vallée Karolina long grain',
  'un riz local produit au Sénégal souvent utilisé pour le ceebu jen.Marque et type : Karolina, Riz de la Vallée brisé',
  '["/api/images/céréales/Riz 2.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-111',
  'PROD-111',
  'Riz 21',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz de la Vallée Brisé de la marque Terral',
  'un riz local produit au Sénégal souvent utilisé pour le ceebu jen.Marque et type : Terral, Riz de la Vallée brisé',
  '["/api/images/céréales/Riz 21.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-112',
  'PROD-112',
  'riz 3',
  'céréales',
  24500,
  24000,
  'Sac de 50 kg',
  1000,
  'kg',
  'Brisures de riz parfumé au jasmin de la marque Royal Umbrella (variété Thaï Hom Mali)',
  'Riz blanc thaïlandais de type jasmin (Hom Mali), composé de grains brisés lors du nettoyage et de la récolte, offrant une texture fondante idéale pour divers plats traditionnels.',
  '["/api/images/céréales/riz 3.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-113',
  'PROD-113',
  'Riz 4',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'Brisures de riz parfumé au jasmin de la marque Royal Umbrella (variété Thaï Hom Mali)',
  'Riz blanc thaïlandais de type jasmin (Hom Mali), composé de grains brisés lors du nettoyage et de la récolte, offrant une texture fondante idéale pour divers plats traditionnels.',
  '["/api/images/céréales/Riz 4.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-114',
  'PROD-114',
  'Riz 6',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz entier parfumé long grain',
  'Riz entier parfumé de marque Sympa (goût riche,o rigine Sénégal)',
  '["/api/images/céréales/Riz 6.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-115',
  'PROD-115',
  'Riz 8',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz rond Supreme d''origine chinoise, reconnaissable à son illustration de la Grande Muraille de Chine sur l''emballage.',
  NULL,
  '["/api/images/céréales/Riz 8.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-116',
  'PROD-116',
  'Riz 9',
  'céréales',
  23000,
  22500,
  'Sac de 50 kg',
  1000,
  'kg',
  'Riz thaï parfumé (riz jasmin) de la marque Royal Umbrella',
  'Riz long grain supérieur (hom mali) naturellement parfumé en provenance directe de Thaïlande.Caractéristiques : Grains d''une blancheur unique au délicat arôme de jasmin, offrant une texture légère et moelleuse après cuisson.',
  '["/api/images/céréales/Riz 9.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-117',
  'PROD-117',
  'Riz1',
  'céréales',
  14000,
  13500,
  'Sac de 50 kg',
  1000,
  'kg',
  'Riz blanc entier à long grains (non parfumé)',
  'Riz Karolina Long Grain de la marque Riz de la Vallée, un produit alimentaire conditionné en grand format.',
  '["/api/images/céréales/Riz1.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-118',
  'PROD-118',
  'Riz10',
  'céréales',
  5000,
  4750,
  'Sac de 5 kg',
  1000,
  'kg',
  'Riz basmati indien LIDO (format 5 kg), un riz à grains longs 100% pur et sans additifs.',
  'Cultivé en Inde, reconnu pour son arôme parfumé et ses grains fins qui ne collent pas.Utilisation : Idéal pour la préparation de divers plats de résistance et de riz sautés.',
  '["/api/images/céréales/Riz10 .jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-119',
  'PROD-119',
  'Riz13',
  'céréales',
  16000,
  15500,
  'Sac de 50 kg',
  1000,
  'kg',
  'Riz jasmin thaïlandais (100 % brisure, double poli et trié).',
  'Produit en Thaïlande et largement consommé en Afrique de l''Ouest, notamment au Sénégal pour la préparation du thieboudienne.',
  '["/api/images/céréales/Riz13.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-120',
  'PROD-120',
  'Riz16',
  'céréales',
  23000,
  22500,
  'Sac de 50 kg',
  1000,
  'kg',
  'Riz parfumé thaïlandais (Thai Hom Mali Rice)',
  'Riz Phitiimi L''Aigle L''Original (100 % brisures, riz parfumé Thai Hom Mali), d''un poids net de 50 kg.',
  '["/api/images/céréales/Riz16.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-121',
  'PROD-121',
  'Riz17',
  'céréales',
  11500,
  11000,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz long grain de qualité supérieure.',
  'Riz soigneusement sélectionné, grains longs et homogènes, adapté à la consommation familiale, aux restaurants et aux commerces. Bonne cuisson et excellent rendement.',
  '["/api/images/céréales/Riz17.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-122',
  'PROD-122',
  'Riz18',
  'céréales',
  11500,
  11000,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz économique et nutritif, idéal pour les repas quotidiens et la restauration.',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène, faible taux de brisure et excellent rendement. Convient à une consommation régulière.',
  '["/api/images/céréales/Riz18.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-123',
  'PROD-123',
  'Riz19',
  'céréales',
  5000,
  4750,
  'Sac de 5 kg',
  1000,
  'kg',
  'Riz économique et nutritif, idéal pour les repas quotidiens et la restauration.',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène, faible taux de brisure et excellent rendement. Convient à une consommation régulière.',
  '["/api/images/céréales/Riz19.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-124',
  'PROD-124',
  'Riz20',
  'céréales',
  13000,
  12750,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz économique Bara bara et nutritif, idéal pour les repas quotidiens et la restauration.',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène, faible taux de brisure et excellent rendement. Convient à une consommation régulière.',
  '["/api/images/céréales/Riz20.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-125',
  'PROD-125',
  'Riz22',
  'céréales',
  9800,
  9650,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz entier non parfumé de la Vallée du fleuve Sénégal, naturel et nutritif.',
  'Le riz Térral est un riz entier non parfumé produit dans la Vallée du fleuve Sénégal. Cultivé localement selon des normes de qualité rigoureuses, il se distingue par ses grains entiers, sa bonne tenue à la cuisson et sa richesse nutritionnelle. Adapté à la préparation de nombreux plats sénégalais, il constitue une alternative locale de qualité aux riz importés. Conditionné en sac de 25 kg pour les ménages, restaurants et commerces.',
  '["/api/images/céréales/Riz22.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-126',
  'PROD-126',
  'Riz23',
  'céréales',
  14000,
  13800,
  'Sac de 50 kg',
  1000,
  'kg',
  'Riz blanc 100 % brisure du Pakistan, économique et adapté à la consommation quotidienne.',
  'Big Joe White Rice est un riz blanc 100 % brisure importé du Pakistan. Apprécié pour sa cuisson rapide, sa texture légère et son excellent rapport qualité-prix, il convient parfaitement aux ménages, restaurants et services de restauration. Ses grains soigneusement sélectionnés garantissent une bonne qualité de cuisson pour les plats traditionnels et modernes. Conditionné en sac de 50 kg pour répondre aux besoins des familles nombreuses et des professionnels.',
  '["/api/images/céréales/Riz23.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-127',
  'PROD-127',
  'Riz24',
  'céréales',
  12000,
  11800,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz de qualité supérieure, grains sélectionnés, cuisson homogène et saveur agréable.',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène, faible taux de brisure et excellent rendement. Convient à une consommation régulière.',
  '["/api/images/céréales/Riz24.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-128',
  'PROD-128',
  'Riz25',
  'céréales',
  12000,
  11800,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz de qualité supérieure, grains sélectionnés, cuisson homogène et saveur agréable.',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène, faible taux de brisure et excellent rendement. Convient à une consommation régulière.',
  '["/api/images/céréales/Riz25.jpeg"]',
  'IN_STOCK',
  0,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-129',
  'PROD-129',
  'Riz5',
  'céréales',
  20500,
  20250,
  'Sac de 50 kg',
  1000,
  'kg',
  'Riz Phitimi l''Aigle, riz blanc de qualité en sac de 50 kg',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène. Facile à cuisiner, il offre une texture agréable et une bonne conservation après cuisson.',
  '["/api/images/céréales/Riz5.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-130',
  'PROD-130',
  'Riz7',
  'céréales',
  18500,
  18250,
  'Sac de 25 kg',
  1000,
  'kg',
  'Riz de qualité supérieure, grains sélectionnés, cuisson homogène et saveur agréable.',
  'Riz de bonne qualité destiné aux ménages, restaurants et revendeurs. Cuisson homogène, faible taux de brisure et excellent rendement. Convient à une consommation régulière.',
  '["/api/images/céréales/Riz7.jpeg"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-131',
  'PROD-131',
  'Thiakry',
  'céréales',
  1500,
  1300,
  'Sachet de 500 g',
  100,
  'kg',
  'Thiakry traditionnel prêt à préparer.',
  'Granulés de mil de qualité supérieure, soigneusement transformés et conditionnés dans un emballage hygiénique. Idéal pour la préparation du thiakry sénégalais avec du lait caillé, du yaourt ou du lait sucré.',
  '["/api/images/céréales/Thiakry.jfif"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);
INSERT OR REPLACE INTO products 
  (id, sku, name, category, price_min, promo_price, unit, stock_quantity, stock_unit,
   short_description, description, images, rarity, active, is_negotiable, created_at)
VALUES (
  'PROD-132',
  'PROD-132',
  'THIERE',
  'céréales',
  1200,
  1000,
  'Sachet de 500 g',
  100,
  'kg',
  'Thiéré traditionnel à base de mil.',
  'Couscous de mil traditionnel sénégalais obtenu à partir de céréales sélectionnées. Convient à plusieurs préparations culinaires et constitue une excellente source d’énergie et de nutriments.',
  '["/api/images/céréales/THIERE.PNG"]',
  'IN_STOCK',
  1,
  0,
  unixepoch()
);

COMMIT;
